---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch Curator and required dependencies.
  pip: "name={{ item }}"
  with_items:
    - elasticsearch-curator
    - argparse

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
  args: "{{ item }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
